relion/_parser/ctffind.py
tests/parser/test_ctffind.py

So this is a bit of work on the parser/ctffind object, which now allows you to get a list of job directories and you can access them by indexing, ie.
`relion.Project(some_path).ctffind["job003"]`

First attempt at handling job folders

---

tests/test_project.py

Handling backslashes is a bit tricky on Windows, so just check that the
final path component is present

Fix path representation check on Windows

---

relion/_parser/class2D.py
tests/parser/test_class2D.py

This adds behaviour to `Class2D` instances so that the object becomes equivalent to
```python
{
"job008": <Path>,
"job013": <Path>,
}
```
That is: We can use `list(class2d)` and `dict(class2d)` and `class2d.values()` and `class2d[jobname]` to get information about the class2d stage and about a specific job within the class2d stage.
(Obviously we will want to eventually get rid of the `<Path>` object in there and replace it with the information contained in that path.)

Turn Class2D into a Mapping

---

src/relion/_parser/class2D.py
src/relion/_parser/class3D.py
src/relion/_parser/ctffind.py
src/relion/_parser/motioncorrection.py
tests/parser/test_class2D.py
tests/parser/test_class3D.py
tests/parser/test_ctffind.py
tests/parser/test_motioncorrection.py

This is a way to avoid double counting when looping over the jobs in a job type directory. All `__iter__` methods have also been changed to call `self.jobs`. This is what was done for class2D already and has been extended so that the other cases match. New tests have been added that create a sym-link inside the test dataset collected by `dials_data` and then test that this sym-link is not included when iterating over jobs. Are there circumstances in which it is desirable to have the alias names and if so could they be stored somewhere else?

Change the iter methods of the different relion job types so that they exclude symbolic links

---

.bumpversion.cfg
setup.cfg
src/relion/__init__.py
src/relion/_parser/class2D.py
src/relion/_parser/class3D.py
src/relion/_parser/ctffind.py
src/relion/_parser/jobtype.py
src/relion/_parser/motioncorrection.py
tests/parser/test_class2D.py
tests/parser/test_class3D.py
tests/parser/test_ctffind.py
tests/parser/test_motioncorrection.py

There is a reasonable amount of shared code between the different job type classes which has been refactored into a `JobType` superclass. Each job type extracts information from loops in a star file in a `_load_job_directory` method. The loop number containing the relevant information was hard-coded. To protect against potential changes to star file structure in different Relion releases a method that searches a star file for a given table heading and returns the loop number has been added. Some tests of `repr` and `str` behaviour have also been added.

Refactor common functionality between job types into a JobType superclass

---

src/relion/_parser/class2D.py
src/relion/_parser/class3D.py
src/relion/_parser/ctffind.py
src/relion/_parser/motioncorrection.py
src/relion/zocalo/wrapper.py

Fixes for the alerts currently raised by LGTM. Removes some `pass` statements from the zocalo wrapper and adds `__eq__` definitions to `JobType` derived classes

Fixes for LGTM alerts

---

src/relion/_parser/jobtype.py

Remove the `lru_cache` decorator from the `_read_star_file` method of `JobType`. The way this cache is implemented would mean that if a file is read and then modified it would not be read again, so updates to that file would not be visible. This is undesirable in the context of the zocalo wrapper which should regularly check for updates throughout the runtime of the Relion pipeline. For now remove the cache and if it is desirable to add caching later it can possibly be added with a check on the file time stamp.

Remove caching of JobType method to read star files

---

src/relion/__init__.py
src/relion/_parser/ctffind.py
src/relion/_parser/jobtype.py
src/relion/_parser/motioncorrection.py
src/relion/_parser/processnode.py

`Project` now inherits from `RelionPipeline`. This allows the project to be iterated over to give all scheduled Relion jobs. A helper class has been added that caches job results and can be set to only return results that have not been seen before.

Change Project to inherit from RelionPipeline and add functionality to collect results by iterating over the Project

---

setup.cfg
setup.py

All package declarations happen inside `setup.cfg`,
`setup.py` is just a tiny piece of code to make `setup.cfg` happen.

Fix entry point declarations

---

src/relion/__init__.py
src/relion/zocalo/wrapper.py

The separate calls to `CTFFind` and `MotionCorr` have been replaced with a loop over `relion_proj.results.fresh` which should just return results that have not been seen before from jobs that have posted a success, as a (Relion stage object, job name) pair. (Note that this has not been extensively tested for correct behaviour.) In order to collect the necessary information `relion_proj.load()` has to be run inside the results collection loop. 
I have also added a check on whether any Relion job failures have been posted before results collection is done. We may have situations where we still want to collect results after a failure has posted so this may need to be moved to a later point or removed but it demonstrates how to do this kind of check. 
I changed the default behaviour of …

Change zocalo wrapper to only collect results that have not already been sent

---

src/relion/__init__.py
src/relion/cryolo_relion_it/cryolo_relion_it.py
src/relion/zocalo/wrapper.py

Fixed some results caching bugs, stop all Relion processes before the wrapper exits by deleting `RUNNING_PIPELINER_PREPROCESS` and  wait for Relion `Import` job to finish before starting to look for results.

Make some changes so that the wrapper runs up to CTF estimation

---

src/relion/__init__.py

Check that the `default_pipeline.star` file can be loaded inside `Project.origin_present()`. I suspect that the wrapper is crashing because there is a slight delay in writing information to `default_pipeline.star` and this extra check should make sure that that has happened before proceeding to attempting to collect resutls.

Make the function that checks if the Relion Import job is present also check that something appears in the pipeline file

---

src/relion/__init__.py
src/relion/_parser/relion_pipeline.py

Stop the pipeline breaking if it gets an empty list from reading a star file.

Small fix to account for empty lists of star values.

---

src/relion/__init__.py
src/relion/_parser/relion_pipeline.py

Use a context manager to check for the presence of the `.relion_lock` directory before accessing the `default_pipeline.star` file. If it doesn't exist create it and remove it once the file has been read. If it does exist wait and try again; timeout after 20 attempts and store the information that there was a failure in the context manager. The method that reads the star file may then check for this failure and return an empty `Document` object instead of attempting to read the file. In the case of a failure the lock directory will not be removed on exit. Some restructuring has been done so that this lock is only applied when the file is actually being read and to allow the necessary information on which files to lock for to be passed from the `Project` class to the `RelionPipeline` class …

Check for the presence of the Relion lock directory before accessing default_pipeline.star

---

src/relion/cryolo_relion_it/cryolo_relion_it.py
src/relion/zocalo/wrapper.py

The wrapper should now run while the `RUNNING_PIPELINER_PREPROCESS` file exists or `cryolo_relion_it.run` is alive. A timeout has been added: when a certain time has elapsed from when Relion was started the `RUNNING_PIPELINER_PREPROCESS` file is deleted. For testing I have hardcoded this to be 2 minutes (clearly not enough in real circumstances). We may want to make this adjustable by putting it in the wrapper somehow, or by triggering the timeout based on session end time.

Wrapper runs until RUNNING_PIPELINER_PREPROCESS is deleted and cryolo_relion_it.run has finished

---

src/relion/_parser/processgraph.py
src/relion/_parser/relion_pipeline.py
src/relion/zocalo/wrapper.py
tests/parser/test_processgraph.py
tests/test_project.py

In #85 a timeout was applied that stopped preprocessing jobs if the last image file is more than 30 minutes old. In the case where processing is done on an old data collection this leads to an earlier exit than is desirable as the preprocessing jobs are stopped quickly and the wrapper may exit without results collection. Here it is required that `cryolo_relion_it` has been running for 10 minutes before the preprocessing jobs can be stopped.
Some changes are also made to reduce the number of times the `default_pipeline.star` file is accessed (which should remove a race condition arising from the fact that we sometimes want those calls to be reading the same star file data) and to stop `_calculate_relative_job_times` from crashing if there are no registered jobs.

Make sure postprocessing jobs are not stopped immediately which was causing the wrapper to exit early

---

src/relion/__init__.py
src/relion/_parser/relion_pipeline.py
src/relion/zocalo/wrapper.py
tests/parser/test_relion_pipeline.py

Currently the 10 minutes after Relion started + 30 minutes after last `Movies` file timeout for deleting `RUNNING_PIPELINER_PREPROCESS` sometimes leads to preprocessing jobs being stopped before they have all completed. It is now required that all preprocessing jobs have run at least once and that all have a last start time that is after the most recent `Movies` file was created before the preprocessing pipeline can be stopped. To do this information from the preprocessing log file is used.

Ensure that preprocessing jobs are not stopped before they have all run at least once

---

requirements_dev.txt
src/relion/_parser/relion_pipeline.py
src/relion/zocalo/wrapper.py
tests/parser/test_relion_pipeline.py

If there are no jobs currently running ("running jobs" are here taken to be jobs that have started according to the log files but not posted a success or failure) and no jobs were submitted in the last 10 minutes then delete the `RUNNING_RELION_IT` file to stop the pipeline. This then allows the wrapper to exit. As things currently are the wrapper waits for `cryolo_relion_it` to stop running which may rely on the manual deletion of the RUNNING file.

Stop Relion processing if there are no currently running jobs and no jobs have been submitted for 10 minutes

---

src/relion/zocalo/wrapper.py

At the moment processing is stopped once all scheduled jobs have completed once and there have been no new micrograph uploads in the last 30 minutes. This time needs extending. The precise amount of time before timeout is not yet precisely specified and is liable to change. To avoid needing to change this hard-coded behaviour in this repository the timeout parameter can be added to the recipe and accessed by the wrapper. This will come with a corresponding change to the relion recipe.

Use a latest movie timeout defined in the recipe rather than hard-coding it

---

src/relion/_parser/relion_pipeline.py

Catch a `FileNotFoundError` when checking modification time of job SUCCESS file and just leave the job status as `None` if one is thrown (equivalent to saying the job is still running).

Fix race condition relating to Relion SUCCESS files

---

src/relion/__init__.py
src/relion/_parser/jobtype.py
src/relion/_parser/processgraph.py
src/relion/zocalo/wrapper.py
tests/parser/test_processgraph.py
tests/test_project.py

Check that all the files in `Import/job001/movies.star` have been through a MotionCorr job by checking the file names against the cached MotionCorr micrograph names (after removing the file extension as it is `tiff` for the Import files and `mrc` for the MotionCorr results). If this check passes then it is only checked again if the list of imported files changes. 
Preprocessing jobs are checked to ensure that they have all been run more recently than the last MotionCorr job that finished the complete set of imported files.

Check that all imported files have been preprocessed before allowing an exit

---

src/relion/__init__.py
src/relion/_parser/class2D.py
src/relion/_parser/class3D.py
src/relion/_parser/ctffind.py
src/relion/_parser/motioncorrection.py
src/relion/zocalo/wrapper.py

These fixes should cover:
* Files disappearing in the `Movies` directory
* The case where `len(int_particle_sum) == 0` crashes 2D and 3D `_class_checker`
* Inability of `gemmi` to read data files, probably due to them being overwritten by Relion at the time
The changes mean that blank data entries are returned when before there would be a crash.

Fixes for race conditions that have shown up during testing

---

requirements.txt
requirements_dev.txt
setup.cfg
src/relion/_parser/ctffind.py
src/relion/_parser/motioncorrection.py
src/relion/zocalo/images_service_plugin.py
src/relion/zocalo/wrapper.py
tests/parser/test_ctffind.py
tests/zocalo/test_images_service_plugin.py

To display Relion output images in SynchWeb we need to convert them from mrc format to jpeg and then insert the path into ISPyB. These changes should provide the infrastructure for doing that (on the wrapper side) for CTF diagnostic plots and motion corrected micrographs. 
The conversion will be done by the DLSImages zocalo service using the `images_service_plugin` provided here. This will require changes to the implementation of the Images service. Sending messages to the service will require a change to the zocalo recipe as well.

Use DLSImages service to convert from mrc to jpeg for CTF diagnostic image and motion corrected micrograph

---

src/relion/cryolo_relion_it/cryolo_relion_it.py
src/relion/cryolo_relion_it/icebreaker_histogram.py
src/relion/zocalo/wrapper.py
tests/cryolo_relion_it/test_icebreaker_external_job.py

The Icebreaker group job currently runs on the `particles.star` output of the Extract job meaning it slows down as more data is collected. Solve this by running on batches and moving to a different schedule so that it doesn't slow down preprocessing

Change Icebreaker group job to run on batches, similar to 2D classification

---

src/relion/cryolo_relion_it/cryolo_relion_it.py
src/relion/zocalo/wrapper.py

Adds the necessary additional options to `RelionItOptions` and runs Relion's own motion correction if the wrapper finds that the `import_images` parameter has a `.eer` extension.

Add EER file format support to the pipeline

---

setup.cfg
src/relion/_parser/autopick.py
src/relion/_parser/cryolo.py
src/relion/dbmodel/modeltables.py
src/relion/zocalo/images_service_plugin.py
src/relion/zocalo/wrapper.py
tests/parser/test_autopick.py
tests/zocalo/test_images_service_plugin.py

The plugin requires a background image, for which we use the motion corrected jpegs that should already exist, and a set of particle coordinates (as well as information on the diameter). Particle coordinates are collected from files and are cached to avoid repeated file scraping in a manner analogous to what is already done for motion correction drift data.

Add image service plugin to make particle picker images

---

setup.cfg

[`src/relion/dbmodel/modeltables.py`](https://github.com/DiamondLightSource/python-relion/blob/21161b1b297318a3591fbafb0bd9d123c54f0457/src/relion/dbmodel/modeltables.py#L5) currently [requires presence of `ispyb` (and `sqlalchemy`)](https://github.com/conda-forge/staged-recipes/pull/16055/checks?check_run_id=3494153661):
```
import: 'relion'
Traceback (most recent call last):
File "/home/conda/staged-recipes/build_artifacts/python-relion_1630575425399/test_tmp/run_test.py", line 2, in <module>
import relion
File "/home/conda/staged-recipes/build_artifacts/python-relion_1630575425399/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.9/site-package …
```

Add ISPyB package dependency

---

src/relion/_parser/relativeicethickness.py

Allows the matching of relative ice thickness five figure results to motion correction records when inserting into ISPyB

Extract motion correction micrograph name from icebreaker five fig paths 

---

src/relion/zocalo/wrapper.py

Use buffer lookup for motion correction results if they are being resent to avoid duplication in the database

Avoid rare motion correction database entry duplication

---

src/relion/zocalo/alchemy.py

Schema for storing some useful information about individual Relion job runs. Not all Relion jobs run on the cluster which is why there are separate `RelionJobInfo` and `ClusterJobInfo` tables. This also allows the "start" time of a job to be stored separate to its "cluster start" time which gives information on queue times.

Add custom ORM for storing pipeline/job run information

---

.azure-pipelines.yml
requirements.txt
requirements_dev.txt
requirements_doc.txt
setup.cfg

and require a newer version of `numpy` for python > 3.7 so that python3.10 tests pass

Fully drop python3.6 support

---

src/relion/cryolo_relion_it/cryolo_relion_it.py
src/relion/zocalo/wrapper.py

If there haven't been any new batches then check that the background process running preprocessing is still alive. If it has exited then finish the thread running Relion. If it exited with a failing error code then remove the file used to stop `relion_it` running. The wrapper currently deletes this file if it is still there at the end of processing, which it should be. We can return a failure state if it isn't as it must have been deleted because of the above preprocessing failure (`relion_it` doesn't remove it anywhere else).

Check preprocessing status if there are no new batches

---

src/relion/__init__.py
src/relion/_parser/relion_pipeline.py
tests/test_project.py

Setting `cluster=True` in the initialisation of a `Project` will collect some job run information such as cluster IDs, cluster job start times and the number of micrographs processed by a particular job from log and output files. It is assumed that the submission script used by Relion will write a line before running the job command in the format:
`$(date '+%Y-%m-%d %H:%M:%S.%3N'): running RELION job on host $(hostname -s) with job ID ${JOB_ID:-(JOB_ID not set)}`
Nothing is done with this information in this PR but it partially addresses #136

Allow the collection of job run information 

---

src/relion/cli/print_default_options.py

Allow configuration of cluster qsub templates

---

src/relion/pipeline/__init__.py
src/relion/zocalo/images_service_plugin.py

For single frame mrcs replace outliers beyond 3 sigma from the mean with the 3 sigma boundary to avoid problems from strange pixel value distributions

Improve mrc to jpeg conversion for cases with outlier pixel values

---

setup.cfg
src/relion/__init__.py
src/relion/_parser/cryolo.py
src/relion/pipeline/__init__.py
src/relion/zocalo/wrapper.py
tests/dbmodel/test_dbnode.py
tests/parser/test_autopick.py
tests/parser/test_class2D.py
tests/parser/test_class3D.py
tests/parser/test_ctffind.py
tests/parser/test_motioncorrection.py
tests/test_project.py

If the Zocalo recipe parameter `"relion_version"` is set to `4` then run the RELION 4 pipeline rather than 3.1. Some changes were required to the processing results parser for `AutoPick` as in RELION 4 crYOLO results go into the `AutoPick` directory as well as RELION's own autopicking. (Also fixes some test related issues.)

Add RELION 4 support to Zocalo wrapper

---

src/relion/_parser/class3D.py
src/relion/_parser/cryolo.py

Single quotes are appearing around keys in `job.star` files from the RELION 4 pipeline. This has caused some problems retrieving data from 3D classification jobs. This problem is addressed here.
crYOLO data parsing is also sped up by removing a loop over micrograph names obtained from the CTF job.

Allow single quotes in job star files and speedup crYOLO data parsing

---

requirements.txt
setup.cfg
src/relion/cli/project_linker.py

Copy necessary files such as star files and make soft links to data directories to avoid duplication of large files. In addition, if possible, hard links are made rather than copies to any files over a set size threshold.

Add a command line tool to copy a RELION project structure

---

setup.cfg
src/relion/zocalo/images_service_plugin.py
src/relion/zocalo/tomo_align.py

Insert plots and images from the tomo_align service rather than adding as attachments in the images service. They can go directly into the Tomogram table now that the fields exist.

Tomogram table changes

---

src/relion/pipeline/__init__.py

If `initial_model.mrc` exists in the InitialModel job directory then use it. Resolves #169

Use initial model suggested by RELION

---

src/relion/_parser/relion_pipeline.py

Currently the initial model class number is collected from the name of the file as determined from `default_pipeline.star`. When using `initial_model.mrc` this can't be done so instead parse the data star file of the initial model job and choose the largest class (not sure if this is strictly correct).

Calculate initial model class number from occupation

---

src/relion/cryolo_relion_it/cryolo_relion_it.py
src/relion/pipeline/__init__.py

Particles picked by cryolo are used to estimate the particle diameter if the option `estimate_particle_diameter` is set to true.
Also included are changes for the new locking methods in CCP-EM pipeliner, and fixes for running class selection if the first batch seen is incomplete.

Use cryolo to calculate the particle diameter

---

requirements.txt
requirements_dev.txt
requirements_doc.txt
setup.cfg
src/relion/cryolo_relion_it/cryolo_relion_it.py
src/relion/pipeline/__init__.py
tests/cryolo_relion_it/test_relion_it_options.py
tests/test_project.py

Convert `RelionItOptions` to a `pydantic.BaseModel` in order to utilise the `pydantic` `root_validator` to calculate extraction box sizes and classification mask diameters according to a provided particle diameter. If the particle diameter is changed the dependencies are recalculated. If `particle_diameter` is left as 0 then these calculations are not performed.

Add particle diameter option

---

src/relion/_parser/combine_star_files.py
src/relion/cryolo_relion_it/cryolo_relion_it.py
src/relion/pipeline/__init__.py
tests/parser/test_combine_star_files.py

When automated 2D class selection is being used just run a single batch of 3D classification. Allow the size of this batch to be varied independently of the 2D classification batch size. Every time a 2D class batch is complete re-run the 3D classification job with the new data until the 3D batch is complete. This will reduce the number of 3D class jobs and will hopefully be more useful

Run a single 3D classification batch

---

src/relion/zocalo/wrapper.py

For backwards compatibility with older pipeline parameters

Allow extract_downscale to not be present in ispyb_parameters
