- .azure-pipelines.yml
- .azure-pipelines/ci-unix.yml
- .azure-pipelines/ci-windows.yml
- .azure-pipelines/ci.yml
- pytest.ini
- relion/FindData-main.py
- relion/FindData.py
- relion/test_find_data.py
- requirements.txt
- requirements_dev.txt
- setup.cfg
- tests/test_MC.py
- tests/test_a_test.py
- tox.ini
Add use of pathlib and dials_data for better data accessibility
> Dials data

- docs/usage.rst
- relion/__init__.py
- tests/test_project.py
this will serve as the entry point to access all project information.
Also write a tiny bit into a `docs/` directory as we go.
> Add a basic project object

- relion/__init__.py
- relion/_parser/ctffind.py
and a way to access this parser class from the relion `Project()` class
> Add a CTFFind parser class

- relion/_parser/class2D.py
- tests/parser/test_class2D.py
- tests/test_overall.py
This slows things down a lot so requires improvement
> Change value references so they are part of the class

- relion/_parser/class2D.py
- relion/_parser/motioncorrection.py
- tests/parser/test_class2D.py
- tests/parser/test_motioncorrection.py
- tests/test_overall.py
Adapt the class to use job-based access
> Motion corr reformat

- relion/_parser/class2D.py
- relion/_parser/ctffind.py
- tests/parser/test_class2D.py
- tests/parser/test_ctffind.py
- tests/test_overall.py
Adapt class to use job-based access
> Ctf reformat

- relion/_parser/class2D.py
- relion/_parser/class3D.py
- tests/parser/test_class2D.py
- tests/parser/test_class3D.py
- tests/test_overall.py
Adapt the class to use job-based access
> Class3d reformat

- relion/parse_project.py
- tests/parser/test_class2D.py
- zocalo/wrapper.py
Add a way to generate Relion zocalo type messages
> Add a command line tool to parse relion project directories

- README.rst
- docs/index.rst
- docs/usage.rst
I've carved out this commit from the other PR, as it is a separate thing
> Documentation updates

- src/relion/_parser/processnode.py
- src/relion/_parser/relion_pipeline.py
This should fix the LGTM warnings introduced by me in #67
> Apply fixes for lgtm warnings

- AUTHORS.rst
- LICENSE
- README.rst
- setup.cfg
- src/relion/cryolo_relion_it/README.md
- src/relion/cryolo_relion_it/cryolo_external_job.py
- src/relion/cryolo_relion_it/cryolo_fine_tune_job.py
- src/relion/cryolo_relion_it/cryolo_relion_it.py
- src/relion/cryolo_relion_it/dls_options.py
- src/relion/cryolo_relion_it/fsc_fitting_external_job.py
- src/relion/cryolo_relion_it/mask_soft_edge_external_job.py
- src/relion/cryolo_relion_it/reconstruct_halves_external_job.py
- src/relion/cryolo_relion_it/relion_zocalo_wrapper.py
- src/relion/cryolo_relion_it/select_and_split_external_job.py
- src/relion/cryolo_relion_it/util_symlink.py
- tests/cryolo_relion_it/test_cryolo_external_job.py
- tests/cryolo_relion_it/test_fsc_fitting_external_job.py
- tests/cryolo_relion_it/test_mask_soft_edge_external_job.py
- tests/cryolo_relion_it/test_reconstruct_halves_external_job.py
- tests/cryolo_relion_it/test_select_and_split_external_job.py
This adds files and their relevant history from the package
https://github.com/DiamondLightSource/python-relion-yolo-it
into this project.
This leads to a license change in the project, which will
now be licensed under BSD3 and GPLv2, with the exception of
the file `src/relion/cryolo_relion_it/cryolo_relion_it.py`,
which will be GPLv2 only.
> Merge package python-relion-yolo-it (d_rel3.1)

- src/relion/zocalo/wrapper.py
Edit the logic to abort Relion if a SynchWeb stop file exists
> Synchweb stop

- .azure-pipelines.yml
- .azure-pipelines/ci-unix.yml
- .azure-pipelines/ci-windows.yml
- .codecov.yml
- requirements_dev.txt
Clone the source and build the package once, then reuse it in all subsequent pipeline steps.
> Update Azure pipeline scripts

- .pre-commit-config.yaml
- pyproject.toml
- requirements.txt
- requirements_dev.txt
- requirements_doc.txt
- setup.cfg
- src/relion/cryolo_relion_it/cryolo_relion_it.py
- src/relion/cryolo_relion_it/dls_options.py
- src/relion/cryolo_relion_it/icebreaker_histogram.py
- src/relion/zocalo/wrapper.py
- tests/cryolo_relion_it/test_icebreaker_external_job.py
There are 3 Icebreaker external jobs added to the cryolo_relion_it script. Their output doesn't affect results further down the pipeline. After the script has finished executing, the code creates a histogram from the Icebreaker grouping output which is saved as a PDF in the Icebreaker directory.
> Add Icebreaker external jobs and histogram

- docs/dbmodel.rst
- src/relion/dbmodel/modeltables.py
- tests/dbmodel/test_table.py
These are review comments for #111.
> Review comments for Table class PR

- src/relion/cryolo_relion_it/cryolo_relion_it.py
and skip check on systems where the `grp` module is not available.
This will address the issue in https://github.com/conda-forge/staged-recipes/pull/16055
> Extract industry user check to function

- requirements_dev.txt
- requirements_doc.txt
- src/relion/__init__.py
- src/relion/_parser/relativeicethickness.py
- src/relion/dbmodel/__init__.py
- src/relion/dbmodel/modeltables.py
- src/relion/zocalo/wrapper.py
- tests/test_project.py
Add methods and wrapper changes to make use of the RelativeIceThickness ISPyB table.
> Relative ice thickness

- .azure-pipelines.yml
- .azure-pipelines/ci-unix.yml
- .azure-pipelines/ci-windows.yml
- requirements_dev.txt
- setup.cfg
Should be quite straightforward
> Python 3.10 support

- src/relion/zocalo/wrapper.py
> Break out of main loop on stop signal

- setup.cfg
- src/relion/zocalo/images_service_plugin.py
- tests/zocalo/test_images_service_plugin.py
Add function to extract the central slice from a 3D tomogram and convert it to JPEG.
> Tomogram central slice

- src/relion/pipeline/__init__.py
> Allow the use of an externally generated 3D reference for 3D classification

- src/relion/pipeline/__init__.py
Use the functions to combine star files in the SPA pipeline. This selects particles from 2D classes and then uses these for the 3D classification
> SPA pipeline class selection

- src/relion/cryolo_relion_it/cryolo_relion_it.py
- src/relion/pipeline/__init__.py
Skip if parameter `class2d_fraction_of_classes_to_remove` is 0
> Allow skipping 2D class selection

- src/relion/__init__.py
- src/relion/_parser/select.py
- src/relion/dbmodel/__init__.py
- src/relion/dbmodel/modeltables.py
Read selected classes from auto-select jobs and update 2D class records so that updates can be sent to ISPyB
> Register 2D classes selected by auto-selection

- src/relion/zocalo/images_service_plugin.py
Clip image histograms to within 3 standard deviations to try and avoid dark images
> Squeeze histograms in tomogram images

- src/relion/zocalo/extract.py
Fourier crop to downscale in the extract job to match RELION. Move downscaling to before normalisation as well to match order in RELION
> Downscale by Fourier cropping
